// site/examples/recipes/solid/PlinkoPreferences.tsx
// #region component
import { createPlinko, type PlinkoBoard } from 'plinko-config';
import { createEffect, onCleanup, onMount } from 'solid-js';

type Channel = 'email' | 'push' | 'sms';

interface Props {
  onChange: (channel: Channel, enabled: boolean) => void;
  /** Read aloud as the board's name. */
  title: string;
}

export function PlinkoPreferences(props: Props) {
  let host!: HTMLDivElement;
  let board: PlinkoBoard<boolean, Channel> | undefined;

  onMount(() => {
    board = createPlinko<boolean, Channel>(host, {
      slots: [
        { id: 'email', label: 'Email', value: 'email' },
        { id: 'push', label: 'Push', value: 'push' },
        { id: 'sms', label: 'SMS', value: 'sms' },
      ],
      chips: [
        { id: 'on', label: 'On', value: true },
        { id: 'off', label: 'Off', value: false },
      ],
    });
    onCleanup(() => board?.destroy());
  });

  // Reactive props go to the live board with update(); the piles stay.
  createEffect(() => {
    const { onChange, title } = props;
    board?.update({
      labels: { board: title },
      onLand: ({ chip, slot }) => {
        if (chip.value !== undefined && slot.value) onChange(slot.value, chip.value);
      },
    });
  });

  return <div ref={host} />;
}
// #endregion component

// site/examples/recipes/react/PlinkoPreferences.tsx
// #region component
import { createPlinko, type LandDetails, type PlinkoBoard } from 'plinko-config';
import { useEffect, useRef } from 'react';

type Channel = 'email' | 'push' | 'sms';

interface Props {
  onChange: (channel: Channel, enabled: boolean) => void;
}

export function PlinkoPreferences({ onChange }: Props) {
  const host = useRef<HTMLDivElement>(null);
  const board = useRef<PlinkoBoard<boolean, Channel>>(undefined);

  // Mount once; destroy on unmount.
  useEffect(() => {
    if (!host.current) return;
    board.current = createPlinko<boolean, Channel>(host.current, {
      slots: [
        { id: 'email', label: 'Email', value: 'email' },
        { id: 'push', label: 'Push', value: 'push' },
        { id: 'sms', label: 'SMS', value: 'sms' },
      ],
      chips: [
        { id: 'on', label: 'On', value: true },
        { id: 'off', label: 'Off', value: false },
      ],
    });
    return () => board.current?.destroy();
  }, []);

  // Fresh callbacks go to the live board; slots and chips stay put, and so do the piles.
  useEffect(() => {
    board.current?.update({
      onLand: ({ chip, slot }: LandDetails<boolean, Channel>) => {
        if (chip.value !== undefined && slot.value) onChange(slot.value, chip.value);
      },
    });
  }, [onChange]);

  return <div ref={host} />;
}
// #endregion component
